name: CI/CD - Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

          echo "MAX_RETRIES=3" >> .env

          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env
          echo "SENDGRID_TEMPLATE_ID=${{ secrets.SENDGRID_TEMPLATE_ID }}" >> .env
          echo "SENDGRID_FROM_EMAIL=${{ secrets.SENDGRID_FROM_EMAIL }}" >> .env
          echo "SENDGRID_API=https://api.sendgrid.com/v3/mail/send" >> .env

          echo "TWILIO_SID=${{ secrets.TWILIO_SID }}" >> .env
          echo "TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }}" >> .env
          echo "TWILIO_FROM=${{ secrets.TWILIO_FROM }}" >> .env

          echo "LIMIT_DATA=100" >> .env
          echo "APP_URL=http://localhost/bulk-communication" >> .env

      - name: Upload .env to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/var/www/bulk-communication/"
